### ISSUE TITLE
Issue: Emoji picker in Carl's Web Dashboard includes unavailable Emoji to Discord

### ISSUE THREAD

**Issue by boktai1000** [CarlGroth/Carl-Bot#10]
Issue noticed on May 17th 2019:

I was trying to add a Role Reaction, and kept running into some odd issues where one of the Role Reactions was absent every time I finished it. After troubleshooting, it appeared that the problem was due to the :star-struck: emoji.

This Emoji is included in the picker on Carl's Dashboard, but is not present in Discord. The end user may assume that it's available as it's listed under "Smileys & People" which one assumes is part of the available built-in emojis.

Additionally, Carl does not appear to provide any sort of error information to the end user that it failed to properly setup the Role / Emoji. As a user, I would expect something akin to the option of not having a channel selected, instead of continuing and finishing the dialog prompt but not achieving the expected end result.

- Trying to create the reaction role in Carl's dashboard, note the :star-struck: emoji used
![image](https://user-images.githubusercontent.com/9054563/57962739-87ed6400-78e0-11e9-9f7d-6e3c97156f10.png)

- Here the emoji :star-struck: can be seen in the picker
![image](https://user-images.githubusercontent.com/9054563/57962746-a2274200-78e0-11e9-9bce-8d7b3d4346bd.png)

- Proceeding with this results in Carl failing silently on including that emoji, but proceeding anyways with only one working emoji
![image](https://user-images.githubusercontent.com/9054563/57962759-d3a00d80-78e0-11e9-90dc-0fb54d76ca49.png)
![image](https://user-images.githubusercontent.com/9054563/57962762-d995ee80-78e0-11e9-94fe-d3007b4572fd.png)

Thank you for designing Carl bot - our Guild loves it and the automation has reduce the workload on our Officer staff from assigning roles. I'm trying to do my due diligence for reporting issues back that we've come across, and this was an odd one.

**Comment by CarlGroth** [comment]
Thanks for the detailed issue. 

I'm aware of several bugs related to the emoji picker and plan on fixing them as soon as I get levels out and school stops stealing all of my time. For what it's worth I generally don't read issues and it's a miracle I saw this within a month of you posting it so for any future stuff please join the support server at https://discord.gg/DSg744v (stuff like this is totally fine to dm me about)
