### ISSUE TITLE
Whitelisted domains still automodded

### ISSUE THREAD

**Issue by repsejnworb** [CarlGroth/Carl-Bot#14]
1. I know this isn't the current source
2. I know no other way to report errors or ask questions 
3. My question is about the source running on carl.gg

So, I have whitelisted `google.com` in the Linkspam part of Automod, yet my users
have their `docs.google.com` links removed.
And I am unable to specify more specific domain-matching like `docs.google.com` as Carl just happily says "Saved" and falls back to not adding it (as `google.com` exists).

**Comment by repsejnworb** [comment]
I guess that is one way to deal with issues.

So let’s not talk about it?
No comment on the issue?
No redirect to another means of communication if that is preferred?

**Comment by CarlGroth** [comment]
Can't repro

If you took even a second to read the aptly named README you would know where to go for questions like these.
