### ISSUE TITLE
Outdated Emoji Version

### ISSUE THREAD

**Issue by VioletStorm** [CarlGroth/Carl-Bot#15]
Carl Bot is not using the same emoji version as discord anymore.

This is an example of the available emojis to discord. (I believe they are using Emoji 12.1.4 now?  I might be wrong though.)
![Screenshot_20200222-131147_Discord](https://user-images.githubusercontent.com/54405427/75099463-cd794480-5576-11ea-9728-daa752101bc8.jpg)

This is an example of the available emojis to Carl Bot, comparing the full list shows that Carl Bot has many missing.
![Screenshot_20200222-131509_Firefox](https://user-images.githubusercontent.com/54405427/75099486-0c0eff00-5577-11ea-8e2c-c68bb58ec184.jpg)

This causes additional issues, most notably being when Carl attempts to use an emoji that has had been altered since the last Emoji version update.  When viewed with a Discord build running the latest Emoji version, twemoji is not able to translate and the emojis are not able to display properly.

This is an example of twemoji failing on emotes that have changed since the last Emoji update. In their place discord puts a darkened out version of the legacy defaults.
![Screenshot_20200222-131826_Discord](https://user-images.githubusercontent.com/54405427/75099548-d7e80e00-5577-11ea-9c47-39b2bc115cb4.jpg)

These are the twemoji emotes that should be displayed.
![Screenshot_20200222-133439_Discord](https://user-images.githubusercontent.com/54405427/75099586-2d241f80-5578-11ea-8398-9db664d87e53.jpg)

To repo those last two screenshots, make sure you are on an updated version of discord that is using Emoji 12+, if you are on an older version the emotes will be inverted.

(viewing on outdated version)
![Screenshot_20200222-134109_Discord](https://user-images.githubusercontent.com/54405427/75099673-395cac80-5579-11ea-9640-ad2d625dddac.jpg)

(viewing same message on current version)
![Screenshot_20200222-134131_Discord](https://user-images.githubusercontent.com/54405427/75099682-4c6f7c80-5579-11ea-839f-1aaec3544656.jpg)

**Comment by CarlGroth** [comment]
Imagine reporting a bug that gets  fixed in an hour and deployed two full weeks later.

(fixed in latest deployment)

**Comment by VioletStorm** [comment]
You're a legend!  ^-^
