### ISSUE TITLE
Why is Carl-bot Being So Stubborn? / Issue With Adding Reaction Roles

### ISSUE THREAD

**Issue by zmkf** [CarlGroth/Carl-Bot#17]
So, I installed Carl-bot for my server, and I've started to use him for adding automatic, "reaction" roles. I used the !rr make command, and everything worked perfectly, right up until it was time to add the roles themselves. I followed the template, so it should've worked, but instead, I got this message: "Uh oh, this is awkward. Please give me a role and remove it to force a refresh." Every. Single. Time. And he (it?) has all the permissions, and everything. I don't know what the problem is. I've tried like twenty times, on mobile, on desktop, with different browsers, with the app...and I get that message every single time.

Why?

**Comment by Gowixx** [comment]
Yeah, Just use the web dashboard, and the bot that he hosts. Dashboard is @ carl.gg

**Comment by hshekwjbdjwkb** [comment]
Gowixx wdym? how do i fix it?

**Comment by TBG-FR** [comment]
@hshekwjbdjwkb It is stated in this repo README that the code is outdated, and only the bot host at https://carl.gg/ is fully functionnal (with another improved code)

However, @CarlGroth  do you think you will be able to update that repo soon ? I'm learning bots development and I'd be really interested to see how you've done things

**Comment by Gowixx** [comment]
I doubt he's going to update it. He's making stacks off of it. And open sourcing big bots with paywalls, or without usually lowers raffic by a lot.

**Comment by Gowixx** [comment]
he's not dead wtf...

**Comment by manmeet-ms** [comment]
![image](https://github.com/user-attachments/assets/20b18995-e79b-4c7d-a5a5-c911b1b09e47)
make sure to give Carl admin perms and place on top of the role order
I was having the same problem in the case of when assigning a role to all members
