### ISSUE TITLE
AttributeError: '<class '__main__.CarlBot'>' object has no attribute 'guilds'

### ISSUE THREAD

**Issue by Kronos11** [CarlGroth/Carl-Bot#2]
where is self.guilds coming from? 
I really like the basis of your bot but would like to fork it and add on, just not sure where guilds is coming from? I'm definitely not an expert in python though.

**Comment by CarlGroth** [comment]
Are you using rewrite?

**Comment by Kronos11** [comment]
Sorry I'm not familiar rewrite?

**Comment by CarlGroth** [comment]
Just pm me on discord, will be easier Carl#0001
