### ISSUE TITLE
Tags cant be added

### ISSUE THREAD

**Issue by Arkhorse** [CarlGroth/Carl-Bot#3]
![rddt test](https://user-images.githubusercontent.com/20694721/41700392-7c8f1482-74fe-11e8-9694-e5009238ff48.png)

The bot role (which it has) can manage roles. There is not a role named that.

**Comment by CarlGroth** [comment]
For future questions, please visit the support server at discord.gg/DSg744v

This problem most likely has to do with the role hierarchy. The way discord decides if you can add a role or not is based on two things: 1. Does the member adding the role have 'manage roles'
2. Is the member trying to add the role higher in the role hierarchy than the role they're trying to add?

I would assume from the very limited information that what you want to do is to drag the bot role above RDDT-test
