### ISSUE TITLE
!rr fix not working

### ISSUE THREAD

**Issue by Erumeldor** [CarlGroth/Carl-Bot#31]
Hello!

The command !rr fix is not working. 

First, if we add a new role on the web GUI the bot does not add the new icon automatically. I mean, sometimes it did it - but most of the time it didn't. 
Also if we delete a role for example, a member of the "admin"-team deleted accidentally the whole reactions (so every reaction on the message) except only the one we removed.

In both cases, we tried to run the command "!rr fix".
The bot answers with "All done" (or similar), but nothing happens. Is this a real bug?

Is there maybe just something we have to change? The carl-bot does have admin privileges.
Thanks

**Comment by StukaRT** [comment]
Some here, trying to use this command to make the roles show up after editing in the dashboard.  Is this suposed behavior? Also what to do to make roles show after an edit? Is there some trick to it?

**Comment by Erumeldor** [comment]
Hi @StukaRT 
I also wrote on the CarlBot discord, because no one answered here.
They said this github is pretty outdated and the issues are kind of lost here.

But they gave me a workaround:

1) Add the reactions yourself
2) Run !rr fixforeign MSG_ID. This will make Carl add reactions on top of yours
3) Remove your reactions

That is kind of annoying but works for us. Hope they will fix the command soon nevertheless.
Have a good one!
