### ISSUE TITLE
Carl Bot not responding to any command

### ISSUE THREAD

**Issue by Kirbo-dev** [CarlGroth/Carl-Bot#35]
4/27/2021, carl bot isnt responding to any command all of sudden, it has never had this problem once in this server. any idea y
![image](https://user-images.githubusercontent.com/82480251/116331170-0cf77e00-a784-11eb-8e94-e0ef21483f74.png)

**Comment by EndsCreed** [comment]
I'm also having this same issue. I also can't login to the website. No idea what's going on. Sorry if this is a necro but the issue is still open with no responses. Plus it appears to still be happening. 

Trying to login just kicks me back to the homepage on carl.gg.
