### ISSUE TITLE
When would the codebase be updated?

### ISSUE THREAD

**Issue by ghost** [CarlGroth/Carl-Bot#38]
I'm just curious when to know when the codebase would be updated as it has been 3 years since it has been updated.

**Comment by DuhonTheGuy** [comment]
I have the same question, but going by how they said "it'll change in the future" and nothing has changed so far, I believe it's not top priority.

**Comment by ghost** [comment]
I think what you're saying is correct because, when the developer is earning stacks from his discord bot, moreover with his bot being used in over 2 million servers, open-sourcing is kind of the "thing" that slows down earnings

**Comment by Moros0741** [comment]
as far as i knew last, the bot was being rewritten in RUST.

**Comment by ghost** [comment]
Oh thanks, BTW where did you get that info from? And I'm working on a Discord bot, wanna help me out?

**Comment by Moros0741** [comment]
A Discord Server for the development team that he works with. If you aren't
already there you are welcome to join the Python Discord Server.
https://discord.gg/python
