### ISSUE TITLE
!set bot channelname

### ISSUE THREAD

**Issue by JestDotty** [CarlGroth/Carl-Bot#4]
is there a way to reset this? I constricted the bot to one channel and I want to undo it.

**Comment by CarlGroth** [comment]
I'm slightly confused by the question, setting a bot channel isn't intrinsically restrictive, restricting commands are. 

Regardless, you did make me realize I had used the wrong message when removing a bot channel, so that has been fixed.

**Comment by CarlGroth** [comment]
Sounds great 😄 if you run into any problems in the future, [the support server](https://discord.gg/DSg744v) is where you can get help fast, it's pretty easy for me to miss github issues.
