### ISSUE TITLE
Carl Bot error 500's me when i click reaction roles

### ISSUE THREAD

**Issue by AG-Ej-Business** [CarlGroth/Carl-Bot#41]
![2021-11-09 11_41_56-Carl-bot Dashboard - Opera](https://user-images.githubusercontent.com/78798556/140909926-a1a44b3b-bef9-4493-a132-8929209d1c72.png)

**Comment by IPranayThakur** [comment]
Go to Discord > Server Settings > Integrations > Carl bot

You'll see what permissions Carl bot is allowed and what are denied. On that screen itself, just check whether Carl Bot has the perms to add reactions and manage roles, if not, go to Carl bot's role settings and enable them manually.

Hopefully, this will solve your issue!

**Comment by Blaton-bat** [comment]
same issue but with logging certain channels
