### ISSUE TITLE
Question: Reaction roles vs existing role membership

### ISSUE THREAD

**Issue by shaggy1395** [CarlGroth/Carl-Bot#5]
I was wondering if there was a way to utilize reaction roles to set up a selection of 4 different team memberships using the "unique" and "once" features to keep each member in only one role, while also preserving existing role memberships?  We have already been using 4 roles to assign teams manually and want to use the bot to manage this going forward.  I've already tested this on my server but wasn't able to find a way.  If a reaction has a choice of Role A or B, and a user who already exists in Role A chooses Role B, they will then be added to both roles since the bot doesn't appear to know about their existing role membership.

**Comment by CarlGroth** [comment]
It's currently being worked on, it will simply be a matter of using both unique and once on the message. Main issue stems from having messages linked together, but I'm sure I will find a way.

**Comment by CarolynCircleTree** [comment]
I want to have the team locked in upon choice.  Is that possible?  I thought once would stop them from choosing again, but it really doesn't seem to do that at all, when used together with unique.  it only adds roles, doesnt remove, but, it doesnt remove the ability to pick another.

**Comment by CarlGroth** [comment]
Like I said, it's being worked on. What you're describing will be possible when it's done.

**Comment by CarlGroth** [comment]
Marking a message as both unique and once (or inverse) will have this behaviour now. Works with links 🎉
